CrazyQuiz/Models/ViewModeles/AdminDashboardViewModel.cs
using System.Collections.Generic;
using CrazyQuiz.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CrazyQuiz.ViewModels
{
    public class AdminDashboardViewModel
    {
        public Quiz Quiz { get; set; }
        public Question Question { get; set; }
        public Answer Answer { get; set; }
        public SelectList QuizList { get; set; }
        public SelectList QuestionList { get; set; }
    }
}

CrazyQuiz/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CrazyQuiz.Models;
using CrazyQuiz.Services.Interfaces;
using CrazyQuiz.ViewModels;
using CrazyQuiz.Services;
using Microsoft.AspNetCore.Authorization;

namespace CrazyQuiz.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class AdminController : Controller
    {
        private readonly IQuestionService _questionService;
        private readonly IAnswerService _answerService;
        private readonly IQuizService _quizService;

        public AdminController(IQuestionService questionService, IAnswerService answerService, IQuizService quizService)
        {
            _questionService = questionService;
            _answerService = answerService;
            _quizService = quizService;
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult AdminDashboard()
        {
            var viewModel = new AdminDashboardViewModel
            {
                Quiz = new Quiz(),
                Question = new Question(),
                Answer = new Answer(),
                QuizList = new SelectList(_quizService.GetAllQuizzes(), "QuizId", "Title"),
                QuestionList = new SelectList(_questionService.GetAllQuestions(), "QuestionId", "Text")
            };

            return View(viewModel);
        }

        public IActionResult ManageQuestions()
        {
            var questions = _questionService.GetAllQuestionsWithQuiz();
            return View(questions);
        }

        public IActionResult DetailsQuestion(int id)
        {
            var question = _questionService.GetQuestionById(id);
            if (question == null)
                return NotFound();

            return View(question);
        }

        public IActionResult CreateQuestion()
        {
            ViewBag.QuizList = new SelectList(_quizService.GetAllQuizzes(), "QuizId", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateQuestion(Question question)
        {
            if (ModelState.IsValid)
            {
                _questionService.CreateQuestion(question);
                return RedirectToAction(nameof(ManageQuestions));
            }

            ViewBag.QuizList = new SelectList(_quizService.GetAllQuizzes(), "QuizId", "Title");
            return View(question);
        }

        public IActionResult EditQuestion(int id)
        {
            var question = _questionService.GetQuestionById(id);
            if (question == null)
                return NotFound();

            ViewBag.QuizList = new SelectList(_quizService.GetAllQuizzes(), "QuizId", "Title", question.QuizId);
            return View(question);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditQuestion(int id, Question question)
        {
            if (ModelState.IsValid)
            {
                _questionService.UpdateQuestion(question);
                return RedirectToAction(nameof(ManageQuestions));
            }

            ViewBag.QuizList = new SelectList(_quizService.GetAllQuizzes(), "QuizId", "Title", question.QuizId);
            return View(question);
        }

        public IActionResult DeleteQuestion(int id)
        {
            var question = _questionService.GetQuestionById(id);
            if (question == null)
                return NotFound();

            return View(question);
        }

        [HttpPost, ActionName("DeleteQuestion")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteQuestionConfirmed(int id)
        {
            _questionService.DeleteQuestion(id);
            return RedirectToAction(nameof(ManageQuestions));
        }

        public IActionResult ManageAnswers()
        {
            var answers = _answerService.GetAllAnswersWithQuestion();
            return View(answers);
        }

        public IActionResult DetailsAnswer(int id)
        {
            var answer = _answerService.GetAnswerById(id);
            if (answer == null)
                return NotFound();

            return View(answer);
        }

        public IActionResult CreateAnswer()
        {
            ViewBag.QuestionList = new SelectList(_questionService.GetAllQuestions(), "QuestionId", "Text");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateAnswer(Answer answer)
        {
            if (ModelState.IsValid)
            {
                _answerService.CreateAnswer(answer);
                return RedirectToAction(nameof(ManageAnswers));
            }

            ViewBag.QuestionList = new SelectList(_questionService.GetAllQuestions(), "QuestionId", "Text");
            return View(answer);
        }

        public IActionResult EditAnswer(int id)
        {
            var answer = _answerService.GetAnswerById(id);
            if (answer == null)
                return NotFound();

            ViewBag.QuestionList = new SelectList(_questionService.GetAllQuestions(), "QuestionId", "Text", answer.QuestionId);
            return View(answer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditAnswer(int id, Answer answer)
        {
            if (ModelState.IsValid)
            {
                _answerService.UpdateAnswer(answer);
                return RedirectToAction(nameof(ManageAnswers));
            }

            ViewBag.QuestionList = new SelectList(_questionService.GetAllQuestions(), "QuestionId", "Text", answer.QuestionId);
            return View(answer);
        }

        public IActionResult DeleteAnswer(int id)
        {
            var answer = _answerService.GetAnswerById(id);
            if (answer == null)
                return NotFound();

            return View(answer);
        }

        [HttpPost, ActionName("DeleteAnswer")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteAnswerConfirmed(int id)
        {
            _answerService.DeleteAnswer(id);
            return RedirectToAction(nameof(ManageAnswers));
        }
    }
}

CrazyQuiz/Controllers/CategoriesController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CrazyQuiz.Models;
using CrazyQuiz.Services.Interfaces;

namespace CrazyQuiz.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IQuizService _quizService;

        public CategoriesController(ICategoryService categoryService, IQuizService quizService)
        {
            _categoryService = categoryService;
            _quizService = quizService;
        }

        public IActionResult Index()
        {
            var categories = _categoryService.GetAllCategories();
            return View(categories);
        }

        public IActionResult Details(int id)
        {
            var category = _categoryService.GetCategoryById(id);
            if (category == null)
                return NotFound();

            return View(category);
        }

        public IActionResult QuizzesByCategory(int categoryId)
        {
            var quizzes = _quizService.GetQuizzesByCategory(categoryId);
            if (!quizzes.Any())
            {
                ViewBag.Message = "No quizzes found from this category.";
            }
            ViewBag.SearchMode = false; 
            return View("QuizList", quizzes); 
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.CreateCategory(category);
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        public IActionResult Edit(int id)
        {
            var category = _categoryService.GetCategoryById(id);
            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.UpdateCategory(category);
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        public IActionResult Delete(int id)
        {
            var category = _categoryService.GetCategoryById(id);
            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _categoryService.DeleteCategory(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

CrazyQuiz/Controllers/QuizzesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CrazyQuiz.Models;
using CrazyQuiz.Services.Interfaces;
using System.Linq;
using CrazyQuiz.Services;

namespace CrazyQuiz.Controllers
{
    public class QuizzesController : Controller
    {
        private readonly IQuizService _quizService;
        private readonly ICategoryService _categoryService;
        private readonly IQuestionService _questionService;

        public QuizzesController(IQuizService quizService, ICategoryService categoryService, IQuestionService questionService)
        {
            _quizService = quizService;
            _categoryService = categoryService;
            _questionService = questionService;
        }

        public IActionResult Index(int page = 1)
        {
            int pageSize = 10;
            var quizzes = _quizService.GetAllQuizzes()
                            .OrderBy(q => q.QuizId)
                            .Skip((page - 1) * pageSize)
                            .Take(pageSize)
                            .ToList();

            return View(quizzes);
        }

        public IActionResult Details(int id)
        {
            var quiz = _quizService.GetQuizById(id);
            if (quiz == null)
                return NotFound();

            return View(quiz);
        }

        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryService.GetAllCategories(), "CategoryId", "Name");
            ViewBag.Difficulties = new SelectList(Enum.GetValues(typeof(QuizDifficulty)));
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Quiz quiz)
        {
            if (ModelState.IsValid)
            {
                _quizService.CreateQuiz(quiz);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categories = new SelectList(_categoryService.GetAllCategories(), "CategoryId", "Name");
            ViewBag.Difficulties = new SelectList(Enum.GetValues(typeof(QuizDifficulty)));
            return View(quiz);
        }

        public IActionResult Edit(int id)
        {
            var quiz = _quizService.GetQuizById(id);
            if (quiz == null)
                return NotFound();

            ViewBag.Categories = new SelectList(_categoryService.GetAllCategories(), "CategoryId", "Name", quiz.CategoryId);
            ViewBag.Difficulties = new SelectList(Enum.GetValues(typeof(QuizDifficulty)), quiz.Difficulty.ToString());
            return View(quiz);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Quiz quiz)
        {
            if (ModelState.IsValid)
            {
                _quizService.UpdateQuiz(quiz);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categories = new SelectList(_categoryService.GetAllCategories(), "CategoryId", "Name", quiz.CategoryId);
            ViewBag.Difficulties = new SelectList(Enum.GetValues(typeof(QuizDifficulty)), quiz.Difficulty.ToString());
            return View(quiz);
        }

        public IActionResult Delete(int id)
        {
            var quiz = _quizService.GetQuizById(id);
            if (quiz == null)
                return NotFound();

            return View(quiz);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _quizService.DeleteQuiz(id);
            return RedirectToAction(nameof(Index));
        }
        /*
        public IActionResult StartQuiz(int id)
        {
            var quiz = _quizService.GetQuizById(id);
            if (quiz == null)
                return NotFound();

            // Încarcă întrebările pentru quiz
            quiz.Questions = _questionService.GetQuestionsByQuiz(id).ToList();

            return View(quiz);
        }
        */
        public IActionResult SearchQuizzes(string searchTerm)
        {
            var quizzes = _quizService.GetAllQuizzes()
                            .Where(q => q.Description.Contains(searchTerm))
                            .ToList();

            if (!quizzes.Any())
            {
                ViewBag.Message = "No quizzes found with the given description.";
            }

            ViewBag.SearchMode = true;
            return View("QuizList", quizzes);
        }
    }
}

CrazyQuiz/Views/Admin/AdminDashboard.cshtml
@model CrazyQuiz.ViewModels.AdminDashboardViewModel

@{
    ViewBag.Title = "Admin Dashboard";
}
<body style="background-image: url('/img/background-home.jpg'); background-size: cover; background-position: center;">

    <div class="d-flex justify-content-center align-items-center" style="margin-top: 150px">
        <div class="btn-group-vertical text-center">
            <a asp-controller="Admin" asp-action="ManageQuestions" class="btn custom-btn btn-lg mb-3">Manage Questions</a>
            <a asp-controller="Admin" asp-action="ManageAnswers" class="btn custom-btn btn-lg mb-3">Manage Answers</a>
            <a asp-controller="Quizzes" asp-action="Index" class="btn custom-btn btn-lg mb-3">Manage Quizzes</a>
            <a asp-controller="Categories" asp-action="Index" class="btn custom-btn btn-lg mb-3">Manage Categories</a>
        </div>
    </div>

    <style>
        .custom-btn {
            background-color: #28a745; /* Verde */
            color: #fff; /* Alb pentru text */
            border: none;
            box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
        }

            .custom-btn:hover {
                background-color: #218838; /* O nuanță mai închisă de verde */
                color: #fff; /* Alb pentru text */
            }
    </style>
</body>

CrazyQuiz/Views/Admin/CreateAnswer.cshtml
@model CrazyQuiz.Models.Answer

<h1>Create Answer</h1>

<form asp-action="CreateAnswer">
    <div class="form-group">
        <label asp-for="Text" class="control-label"></label>
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input asp-for="IsCorrect" class="form-check-input" />
            <label class="form-check-label" asp-for="IsCorrect">Is Correct</label>
        </div>
        <span asp-validation-for="IsCorrect" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Question" class="control-label"></label>
        <select asp-for="QuestionId" class="form-control" asp-items="ViewBag.QuestionList"></select>
        <span asp-validation-for="QuestionId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

CrazyQuiz/Views/Admin/CreateQuestion.cshtml
@model CrazyQuiz.Models.Question
@{
    ViewData["Title"] = "Create Question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Question</h1>

<form asp-action="CreateQuestion">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Text" class="control-label"></label>
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Quiz" class="control-label"></label>
        <select asp-for="QuizId" class="form-control" asp-items="ViewBag.QuizList"></select>
        <span asp-validation-for="QuizId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

CrazyQuiz/Views/Admin/DeleteAnswer.cshtml
@model CrazyQuiz.Models.Answer
@{
    ViewBag.Title = "Delete Question";
}
<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Answer Text:</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsCorrect)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsCorrect)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question.Text)
        </dd>
    </dl>
    <form asp-action="DeleteAnswer">
        <input type="hidden" asp-for="AnswerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ManageAnswers">Back to List</a>
    </form>
</div>

CrazyQuiz/Views/Admin/DeleteQuestion.cshtml
@model CrazyQuiz.Models.Question
@using Microsoft.AspNetCore.Mvc.Rendering
@using Microsoft.AspNetCore.Mvc.ViewFeatures

@{
    ViewBag.Title = "Delete";
}
<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quiz)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quiz.Title)
        </dd>
    </dl>
    <form asp-action="DeleteQuestion">
        <input type="hidden" asp-for="QuestionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ManageQuestion">Back to List</a>
    </form>
</div>

CrazyQuiz/Views/Admin/DetailsAnswer.cshtml
@model CrazyQuiz.Models.Answer

<h1>Answer Details</h1>

<div>
    <h4>Answer Text:</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsCorrect)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsCorrect)
        </dd>
        <dt class="col-sm-2">
            Question
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Question.Text)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="EditAnswer" asp-route-id="@Model.AnswerId">Edit</a> |
    <a asp-action="ManageAnswers">Back to List</a>
</p>

CrazyQuiz/Views/Admin/DetailsQuestion.cshtml
@model CrazyQuiz.Models.Question

<h1>Question Details</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
    <dl class="row">
        <dt>
            @Html.DisplayNameFor(model => model.Quiz)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quiz.Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="EditQuestion" asp-route-id="@Model.QuestionId">Edit</a> |
    <a asp-action="ManageQuestions">Back to List</a>
</div>
 

CrazyQuiz/Views/Admin/EditAnswer.cshtml
@model CrazyQuiz.Models.Answer

@{
    ViewBag.Title = "Edit Quiz";
}

<h2>@ViewBag.Title</h2>

<form asp-action="EditAnswer" method="post">
    <input type="hidden" asp-for="AnswerId" />
    <div class="form-group">
        <label asp-for="Text" class="control-label"></label>
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input asp-for="IsCorrect" class="form-check-input" />
            <label class="form-check-label" asp-for="IsCorrect">Is Correct</label>
        </div>
        <span asp-validation-for="IsCorrect" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="QuestionId" class="control-label"></label>
        <select asp-for="QuestionId" class="form-control" asp-items="ViewBag.QuestionList"></select>
        <span asp-validation-for="QuestionId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</form>

CrazyQuiz/Views/Admin/EditQuestion.cshtml
@model CrazyQuiz.Models.Question

<h1>Edit Question</h1>

<form asp-action="EditQuestion">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Text" class="control-label"></label>
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="QuizId" class="control-label"></label>
        <select asp-for="QuizId" class="form-control" asp-items="ViewBag.QuizList"></select>
        <span asp-validation-for="QuizId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

CrazyQuiz/Views/Admin/ManageAnswers.cshtml
@model IEnumerable<CrazyQuiz.Models.Answer>

<h1>Manage Answers</h1>

<p>
    <a asp-action="CreateAnswer"  class="btn btn-primary">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Answer Text</th>
            <th>Question Text</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var answer in Model)
        {
            <tr>
                <td>@answer.Text</td>
                <td>@answer.Question.Text</td>
                <td>
                    <a asp-action="DetailsAnswer" asp-route-id="@answer.AnswerId">Details</a> |
                    <a asp-action="EditAnswer" asp-route-id="@answer.AnswerId">Edit</a> |
                    <a asp-action="DeleteAnswer" asp-route-id="@answer.AnswerId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

CrazyQuiz/Views/Admin/ManageQuestions.cshtml
@model IEnumerable<CrazyQuiz.Models.Question>


@{
    ViewData["Title"] = "Manage Questions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Manage Questions</h1>

<p>
    <a asp-action="CreateQuestion" class="btn btn-primary">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Question Text</th>
            <th>Quiz Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var question in Model)
        {
            <tr>
                <td>@question.Text</td>
                <td>@question.Quiz.Title</td>
                <td>
                    <a asp-action="DetailsQuestion" asp-route-id="@question.QuestionId">Details</a> |
                    <a asp-action="EditQuestion" asp-route-id="@question.QuestionId">Edit</a> |
                    <a asp-action="DeleteQuestion" asp-route-id="@question.QuestionId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>